[package]
name = "day_06"
version = "0.1.0"
authors = ["Derek Witt <derekw023@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "day_06"
path = "main.rs"
